// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_DoAn.Data;

#nullable disable

namespace WebAPI_DoAn.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    partial class ShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI_DoAn.Models.Domain.LoaiSanPham", b =>
                {
                    b.Property<int>("IdLoaiSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLoaiSP"));

                    b.Property<string>("ImgLSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLoaiSP");

                    b.ToTable("loaiSanPhams");
                });

            modelBuilder.Entity("WebAPI_DoAn.Models.Domain.NhanVien", b =>
                {
                    b.Property<int>("IdNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNV"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNV")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNV");

                    b.ToTable("nhanViens");
                });

            modelBuilder.Entity("WebAPI_DoAn.Models.Domain.NhanVienShop", b =>
                {
                    b.Property<int>("NhanVienShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanVienShopId"));

                    b.Property<int?>("IdNV")
                        .HasColumnType("int");

                    b.Property<int?>("Idsp")
                        .HasColumnType("int");

                    b.Property<int?>("NhanVienIdNV")
                        .HasColumnType("int");

                    b.Property<int?>("shopIdsp")
                        .HasColumnType("int");

                    b.HasKey("NhanVienShopId");

                    b.HasIndex("NhanVienIdNV");

                    b.HasIndex("shopIdsp");

                    b.ToTable("nhanVienShops");
                });

            modelBuilder.Entity("WebAPI_DoAn.Models.Domain.shop", b =>
                {
                    b.Property<int>("Idsp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idsp"));

                    b.Property<int>("GiaTien")
                        .HasColumnType("int");

                    b.Property<int?>("IdLoaiSP")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrendingProduct")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("loaiSanPhamIdLoaiSP")
                        .HasColumnType("int");

                    b.HasKey("Idsp");

                    b.HasIndex("loaiSanPhamIdLoaiSP");

                    b.ToTable("shops");
                });

            modelBuilder.Entity("WebAPI_DoAn.Models.Domain.NhanVienShop", b =>
                {
                    b.HasOne("WebAPI_DoAn.Models.Domain.NhanVien", "NhanVien")
                        .WithMany("nhanVienShops")
                        .HasForeignKey("NhanVienIdNV");

                    b.HasOne("WebAPI_DoAn.Models.Domain.shop", "shop")
                        .WithMany("nhanvienshop")
                        .HasForeignKey("shopIdsp");

                    b.Navigation("NhanVien");

                    b.Navigation("shop");
                });

            modelBuilder.Entity("WebAPI_DoAn.Models.Domain.shop", b =>
                {
                    b.HasOne("WebAPI_DoAn.Models.Domain.LoaiSanPham", "loaiSanPham")
                        .WithMany("shops")
                        .HasForeignKey("loaiSanPhamIdLoaiSP");

                    b.Navigation("loaiSanPham");
                });

            modelBuilder.Entity("WebAPI_DoAn.Models.Domain.LoaiSanPham", b =>
                {
                    b.Navigation("shops");
                });

            modelBuilder.Entity("WebAPI_DoAn.Models.Domain.NhanVien", b =>
                {
                    b.Navigation("nhanVienShops");
                });

            modelBuilder.Entity("WebAPI_DoAn.Models.Domain.shop", b =>
                {
                    b.Navigation("nhanvienshop");
                });
#pragma warning restore 612, 618
        }
    }
}
